# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-Ja280bBHAPeTkqwWNxGhpEKrM-tJqe
"""

mydictionarys={}

for char in "hey":
  if char in mydictionarys:
    mydictionarys[char]=mydictionarys[char]+1
  else:
    mydictionarys[char]=1

print(mydictionarys)

# tuple
#tuple => immutable
tuple1=1,2,3,4,"hey"

mydictionarys={1:"ali", 2:"aman", 3:"jaipur"}
print(mydictionarys)

mydictionarys={1:"ali", 2:"aman", 3:"jaipur"}
print(mydictionarys)
len(mydictionarys)

mydictionarys={1:"ali", 2:"aman", 3:"jaipur"}
mydictionarys[3]="jodhpur" #update
print(mydictionarys)

mydictionarys={1:"ali", 2:"aman", 3:"jaipur"}
mydictionarys[3]="jodhpur" #update
mydictionarys[4]="delhi" #add

print(mydictionarys)

mydictionarys={1:"ali", 2:"aman", 3:"jaipur"}
mydictionarys.pop(3)
print(mydictionarys)

x=(10,20)
a=x[0]
b=x[1]

print(a,b)

x=(10,20)
a,b=x #tuple unpacking
print(a,b)

mydictionarys={"x": 100}
mydictionarys["x"]=mydictionarys["x"]+100
print(mydictionarys)

mydictionarys={"count":0}
string1="hello heyadf"
for i in string1:
  if i in "aeiou":
    mydictionarys["count"]=mydictionarys["count"]+1
print(mydictionarys)

mydictionarys={}

for char in "hey":
  mydictionarys[char]=1
print(mydictionarys)

mydictionarys={}

for char in "hey":
  if char not in mydictionarys:
    mydictionarys[char]=1
  else:
    mydictionarys[char]=mydictionarys[char]+1

print(mydictionarys)

mydictionarys={}

for char in "heey hello":
  if char in "aeiou":
    if char not in mydictionarys:
      mydictionarys[char]=1
    else:
      mydictionarys[char]=mydictionarys[char]+1

print(mydictionarys)

dic={1:0,2:1,3:2,7:3,11:4,13:5}
k=9

for i in dic:
  if k-i in dic:

    print(i,dic[i])

dic1={1:"rahul", 2:"ali", 3:"aman"}
dic1[4]="jaipur"
print(dic1)

mydic={"count":0}
string1="hello"
for i in string1:
  mydic["count"]=mydic["count"]+1
print(mydic)

mydic={"count":0}
string1="hello heyadf"
for i in string1:
  if i in "aeiou":
    mydic["count"]=mydic["count"]+1
print(mydic)

mydic={}
str1="heey"
for i in str1:
  if i not in mydic:
    mydic[i]=1
  else:
    mydic[i]=mydic[i]+1
print(mydic)

dic1={1:0,2:1,3:2,7:3,11:4,13:5}
k=9
for i in dic1:
  if k-i in dic1:
   print(dic1[i],i)

list1=[]
for i in range(1,50):
  if i%2!=0:
    list1.append(i)
print(list1)

s="(()"
mylist=[]
x=0
for char in s:
  if char=="(":
    mylist.append(char)
  elif char==")" and "("!=mylist.pop():
    x=1
    break
if x==1 or len(mylist)>0 :
  print("invalid")
else:
  print("valid")

# anagram
#s="tyu"
a="uyt"
b="yut"
dic1={}
for i in a:
  if i not in dic1:
    dic1[i]=1
  else:
    dic1[i]=dic1[i]+1
dic2={}
for i in b:
  if i not in dic2:
    dic2[i]=1
  else:
    dic2[i]=dic2[i]+1
if dic1==dic2:
  print("valid anagram")
else:
  print("invalid anagram")

